// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranslaCat.Chat.Infrastructure.Persistence;

#nullable disable

namespace TranslaCat.Chat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260926153440_InitialChat")]
    partial class InitialChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatAiAgentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("Active")
                        .HasColumnType("bit(1)")
                        .HasColumnName("active");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("original_language_code");

                    b.Property<string>("PersonaPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("persona_prompt");

                    b.Property<string>("ProfileBackgroundImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_background_image_object_key");

                    b.Property<string>("ProfileImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_image_object_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("chat_ai_agent", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatAiSystemSettingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("id");

                    b.Property<int>("ContextMaxCharacters")
                        .HasColumnType("int")
                        .HasColumnName("context_max_characters");

                    b.Property<int>("ContextMaxMessages")
                        .HasColumnType("int")
                        .HasColumnName("context_max_messages");

                    b.Property<int>("ConversationCooldownSeconds")
                        .HasColumnType("int")
                        .HasColumnName("conversation_cooldown_seconds");

                    b.Property<int>("ConversationMinHumanMessagesAfterAi")
                        .HasColumnType("int")
                        .HasColumnName("conversation_min_human_messages_after_ai");

                    b.Property<int>("ConversationResponseRate")
                        .HasColumnType("int")
                        .HasColumnName("conversation_response_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxAiMembersPerRoom")
                        .HasColumnType("int")
                        .HasColumnName("max_ai_members_per_room");

                    b.Property<int>("MentionRateLimitCount")
                        .HasColumnType("int")
                        .HasColumnName("mention_rate_limit_count");

                    b.Property<int>("MentionRateLimitWindowSeconds")
                        .HasColumnType("int")
                        .HasColumnName("mention_rate_limit_window_seconds");

                    b.Property<int>("ReplyMaxCharacters")
                        .HasColumnType("int")
                        .HasColumnName("reply_max_characters");

                    b.Property<ulong>("ResponseDelayEnabled")
                        .HasColumnType("bit(1)")
                        .HasColumnName("response_delay_enabled");

                    b.Property<int>("ResponseDelayMaxMillis")
                        .HasColumnType("int")
                        .HasColumnName("response_delay_max_millis");

                    b.Property<int>("ResponseDelayMinMillis")
                        .HasColumnType("int")
                        .HasColumnName("response_delay_min_millis");

                    b.Property<TimeSpan>("RevivalAllowedEndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("revival_allowed_end_time");

                    b.Property<TimeSpan>("RevivalAllowedStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("revival_allowed_start_time");

                    b.Property<int>("RevivalFirstDelayHours")
                        .HasColumnType("int")
                        .HasColumnName("revival_first_delay_hours");

                    b.Property<int>("RevivalSecondDelayHours")
                        .HasColumnType("int")
                        .HasColumnName("revival_second_delay_hours");

                    b.Property<int>("RevivalThirdDelayHours")
                        .HasColumnType("int")
                        .HasColumnName("revival_third_delay_hours");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("chat_ai_system_setting", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AiRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ai_request_id");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('SYSTEM','TEXT')")
                        .HasColumnName("message_type");

                    b.Property<long?>("SenderAiMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_ai_member_id");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('AI','SYSTEM','USER')")
                        .HasColumnName("sender_type");

                    b.Property<long?>("SenderUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('DELETED','SENT')")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatRoomId", "CreatedAt", "Id" }, "idx_chat_message_room_created_id")
                        .HasDatabaseName("idx_chat_message_room_created_id");

                    b.HasIndex(new[] { "ChatRoomId", "Id" }, "idx_chat_message_room_id_id")
                        .HasDatabaseName("idx_chat_message_room_id_id");

                    b.HasIndex(new[] { "SenderAiMemberId" }, "idx_chat_message_sender_ai_member_id")
                        .HasDatabaseName("idx_chat_message_sender_ai_member_id");

                    b.HasIndex(new[] { "AiRequestId" }, "uk_chat_message_ai_request_id")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_message_ai_request_id");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatMessageTranslationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_message_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('COMPLETED','FAILED','PENDING')")
                        .HasColumnName("status");

                    b.Property<string>("TranslatedContent")
                        .HasColumnType("text")
                        .HasColumnName("translated_content");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatMessageId" }, "idx_chat_translation_message_id")
                        .HasDatabaseName("idx_chat_translation_message_id");

                    b.HasIndex(new[] { "Status" }, "idx_chat_translation_status")
                        .HasDatabaseName("idx_chat_translation_status");

                    b.HasIndex(new[] { "ChatMessageId", "LanguageCode" }, "uk_chat_message_translation_message_language")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_message_translation_message_language");

                    b.ToTable("chat_message_translation", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatNotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<long?>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<ulong>("IsRead")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("enum('CHAT_INVITATION','OPEN_CHAT_KICKED','OPEN_CHAT_ROLE_CHANGED','OPEN_CHAT_ROOM_CLOSED')")
                        .HasColumnName("notification_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("SourceEventKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("source_event_key");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RecipientUserId", "CreatedAt" }, "idx_chat_notification_recipient_created")
                        .HasDatabaseName("idx_chat_notification_recipient_created");

                    b.HasIndex(new[] { "RecipientUserId", "IsRead", "Id" }, "idx_chat_notification_recipient_read_id")
                        .HasDatabaseName("idx_chat_notification_recipient_read_id");

                    b.HasIndex(new[] { "ChatRoomId" }, "idx_chat_notification_room_id")
                        .HasDatabaseName("idx_chat_notification_room_id");

                    b.HasIndex(new[] { "RecipientUserId", "NotificationType", "SourceEventKey" }, "uk_chat_notification_recipient_type_source")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_notification_recipient_type_source");

                    b.ToTable("chat_notification", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiActivityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime?>("ClaimExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("claim_expires_at");

                    b.Property<string>("ClaimToken")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("claim_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("LastHumanMessageAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_human_message_at");

                    b.Property<long?>("LastHumanMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_human_message_id");

                    b.Property<long?>("LastRevivalAiMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_revival_ai_member_id");

                    b.Property<DateTime?>("LastRevivalAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_revival_at");

                    b.Property<DateTime?>("NextRevivalAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_revival_at");

                    b.Property<long>("RevivalCycleVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("revival_cycle_version");

                    b.Property<int>("RevivalStage")
                        .HasColumnType("int")
                        .HasColumnName("revival_stage");

                    b.Property<ulong>("RevivalStopped")
                        .HasColumnType("bit(1)")
                        .HasColumnName("revival_stopped");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClaimExpiresAt" }, "idx_chat_room_ai_activity_claim")
                        .HasDatabaseName("idx_chat_room_ai_activity_claim");

                    b.HasIndex(new[] { "RevivalStopped", "NextRevivalAt" }, "idx_chat_room_ai_activity_revival_due")
                        .HasDatabaseName("idx_chat_room_ai_activity_revival_due");

                    b.HasIndex(new[] { "ChatRoomId" }, "uk_chat_room_ai_activity_room")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_room_ai_activity_room");

                    b.ToTable("chat_room_ai_activity", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiMemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("Active")
                        .HasColumnType("bit(1)")
                        .HasColumnName("active");

                    b.Property<long>("AiAgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_agent_id");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("left_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AiAgentId", "Active" }, "idx_chat_room_ai_member_agent_active")
                        .HasDatabaseName("idx_chat_room_ai_member_agent_active");

                    b.HasIndex(new[] { "ChatRoomId", "Active" }, "idx_chat_room_ai_member_room_active")
                        .HasDatabaseName("idx_chat_room_ai_member_room_active");

                    b.HasIndex(new[] { "ChatRoomId", "AiAgentId" }, "uk_chat_room_ai_member_room_agent")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_room_ai_member_room_agent");

                    b.ToTable("chat_room_ai_member", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<ulong>("ConversationEnabled")
                        .HasColumnType("bit(1)")
                        .HasColumnName("conversation_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("DisclosureType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("enum('PRIVATE','PUBLIC')")
                        .HasColumnName("disclosure_type");

                    b.Property<string>("MentionPermission")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('ALL_MEMBERS','OWNER_ADMIN_ONLY')")
                        .HasColumnName("mention_permission");

                    b.Property<ulong>("RevivalEnabled")
                        .HasColumnType("bit(1)")
                        .HasColumnName("revival_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatRoomId" }, "uk_chat_room_ai_setting_room")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_room_ai_setting_room");

                    b.ToTable("chat_room_ai_setting", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("Active")
                        .HasColumnType("bit(1)")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('DIRECT','GROUP','OPEN')")
                        .HasColumnName("room_type");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('AI','FRIEND','MANUAL','OPEN')")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OwnerId" }, "idx_chat_room_owner_id")
                        .HasDatabaseName("idx_chat_room_owner_id");

                    b.HasIndex(new[] { "RoomType" }, "idx_chat_room_room_type")
                        .HasDatabaseName("idx_chat_room_room_type");

                    b.HasIndex(new[] { "SourceType" }, "idx_chat_room_source_type")
                        .HasDatabaseName("idx_chat_room_source_type");

                    b.ToTable("chat_room", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("Active")
                        .HasColumnType("bit(1)")
                        .HasColumnName("active");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_read_at");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_message_id");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("left_at");

                    b.Property<string>("OriginalLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("original_language_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('ADMIN','MEMBER','OWNER')")
                        .HasColumnName("role");

                    b.Property<ulong>("ShowOriginal")
                        .HasColumnType("bit(1)")
                        .HasColumnName("show_original");

                    b.Property<ulong>("ShowTranslation")
                        .HasColumnType("bit(1)")
                        .HasColumnName("show_translation");

                    b.Property<string>("TranslationLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("translation_language_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChatRoomId", "Active" }, "idx_chat_room_member_room_active")
                        .HasDatabaseName("idx_chat_room_member_room_active");

                    b.HasIndex(new[] { "UserId", "Active" }, "idx_chat_room_member_user_active")
                        .HasDatabaseName("idx_chat_room_member_user_active");

                    b.HasIndex(new[] { "ChatRoomId", "UserId" }, "uk_chat_room_member_room_user")
                        .IsUnique()
                        .HasDatabaseName("uk_chat_room_member_room_user");

                    b.ToTable("chat_room_member", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatBanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("banned_at");

                    b.Property<long>("BannedByMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("banned_by_member_id");

                    b.Property<string>("BannedByRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('ADMIN','MEMBER','OWNER')")
                        .HasColumnName("banned_by_role");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("LastJoinedAtSnapshot")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_joined_at_snapshot");

                    b.Property<string>("NicknameSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname_snapshot");

                    b.Property<string>("ProfileImageObjectKeySnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_image_object_key_snapshot");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("released_at");

                    b.Property<long?>("ReleasedByMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("released_by_member_id");

                    b.Property<long>("TargetChatRoomMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_chat_room_member_id");

                    b.Property<string>("TargetMemberCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("target_member_code");

                    b.Property<string>("TargetRoleSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("enum('ADMIN','MEMBER','OWNER')")
                        .HasColumnName("target_role_snapshot");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("BannedByMemberId");

                    b.HasIndex("ReleasedByMemberId");

                    b.HasIndex("TargetChatRoomMemberId");

                    b.HasIndex(new[] { "TargetMemberCode" }, "idx_open_chat_ban_member_code")
                        .HasDatabaseName("idx_open_chat_ban_member_code");

                    b.HasIndex(new[] { "ChatRoomId", "ReleasedAt", "Id" }, "idx_open_chat_ban_room_active_id")
                        .HasDatabaseName("idx_open_chat_ban_room_active_id");

                    b.HasIndex(new[] { "ChatRoomId", "TargetUserId", "ReleasedAt" }, "idx_open_chat_ban_room_user_active")
                        .HasDatabaseName("idx_open_chat_ban_room_user_active");

                    b.ToTable("open_chat_ban", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatMemberProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatRoomMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_member_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("member_code");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("ProfileImageObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("profile_image_object_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nickname" }, "idx_open_chat_member_profile_nickname")
                        .HasDatabaseName("idx_open_chat_member_profile_nickname");

                    b.HasIndex(new[] { "MemberCode" }, "uk_open_chat_member_profile_code")
                        .IsUnique()
                        .HasDatabaseName("uk_open_chat_member_profile_code");

                    b.HasIndex(new[] { "ChatRoomMemberId" }, "uk_open_chat_member_profile_member")
                        .IsUnique()
                        .HasDatabaseName("uk_open_chat_member_profile_member");

                    b.ToTable("open_chat_member_profile", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatRoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatRoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxMemberCount")
                        .HasColumnType("int")
                        .HasColumnName("max_member_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("enum('ACTIVE','CLOSED')")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("enum('PUBLIC','UNLISTED')")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Status" }, "idx_open_chat_room_status")
                        .HasDatabaseName("idx_open_chat_room_status");

                    b.HasIndex(new[] { "Visibility", "Status" }, "idx_open_chat_room_visibility_status")
                        .HasDatabaseName("idx_open_chat_room_visibility_status");

                    b.HasIndex(new[] { "ChatRoomId" }, "uk_open_chat_room_chat_room")
                        .IsUnique()
                        .HasDatabaseName("uk_open_chat_room_chat_room");

                    b.ToTable("open_chat_room", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.UserChatLanguageSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("original_language_code");

                    b.Property<ulong>("ShowOriginal")
                        .HasColumnType("bit(1)")
                        .HasColumnName("show_original");

                    b.Property<ulong>("ShowTranslation")
                        .HasColumnType("bit(1)")
                        .HasColumnName("show_translation");

                    b.Property<string>("TranslationLanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("translation_language_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_chat_language_setting_user")
                        .HasDatabaseName("idx_user_chat_language_setting_user");

                    b.HasIndex(new[] { "UserId" }, "uk_user_chat_language_setting_user")
                        .IsUnique()
                        .HasDatabaseName("uk_user_chat_language_setting_user");

                    b.ToTable("user_chat_language_setting", (string)null);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("SenderAiMemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatMessageTranslationEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatNotificationEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiActivityEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithOne()
                        .HasForeignKey("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiActivityEntity", "ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiMemberEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatAiAgentEntity", null)
                        .WithMany()
                        .HasForeignKey("AiAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiSettingEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithOne()
                        .HasForeignKey("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomAiSettingEntity", "ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatBanEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("BannedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleasedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetChatRoomMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatMemberProfileEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomMemberEntity", null)
                        .WithOne()
                        .HasForeignKey("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatMemberProfileEntity", "ChatRoomMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatRoomEntity", b =>
                {
                    b.HasOne("TranslaCat.Chat.Infrastructure.Persistence.Entities.ChatRoomEntity", null)
                        .WithOne()
                        .HasForeignKey("TranslaCat.Chat.Infrastructure.Persistence.Entities.OpenChatRoomEntity", "ChatRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
