bind 0.0.0.0
port 6379
protected-mode yes
databases 1
aclfile /run/chat/users.acl

maxmemory 256mb
maxmemory-policy noeviction
timeout 0
tcp-keepalive 60
loglevel notice
logfile ""

save ""
appendonly no
dir /data
